version: 0.2

phases:
  build:
    commands:
    - mvn clean package -Ppublishing,staging -Dfindbugs.skip -DskipTests -Dcheckstyle.skip -Dadditionalparam=-Xdoclint:none -DuseAgent=false -Dzip.generation.additional.files.sources=/var/sdk/additional-files-to-copy -e
